apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vidhya101/argocdplugin-terraform-lab.git'
    targetRevision: HEAD
    path: 'terraform'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
